name: CI/CD for Static HTML Application

on:
  push:
    branches:
      - test # Desencadenar en la rama test para desplegar en la instancia de prueba
  pull_request:
    branches:
      - main # Desplegar cuando se haga un PR hacia la rama master

jobs:
  # Trabajo 1: Desplegar en EC2 instancia de prueba
  deploy_to_test:
    name: Deploy Static HTML App to Test EC2 Instance
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test' # Solo se ejecuta en un push a la rama test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key for Test Instance
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2 Test Instance
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_INSTANCE }} # IP o dominio de la instancia EC2 de prueba
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }} # La clave SSH de tu instancia EC2
          port: 22
          script: |
            # Cambiar al directorio donde se almacenarán los archivos estáticos
            cd /home/ec2-user/app
            git pull origin test # Asegúrate de obtener los últimos cambios de la rama test
            # Copiar los archivos estáticos a la carpeta donde se sirven los archivos
            cp -r * /var/www/html # Asumiendo que tu servidor está configurado para servir archivos en /var/www/html

  # Trabajo 2: Desplegar en EC2 instancias de producción
  deploy_to_production:
    name: Deploy Static HTML App to Production EC2 Instances
    runs-on: ubuntu-latest
    needs: deploy_to_test # Este trabajo depende de que el despliegue en la instancia de test termine
    if: github.event_name == 'pull_request' # Solo se ejecuta en un PR hacia 'main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key for Production Instances
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Paso 1: Desplegar en la instancia EC2 1 (Producción)
      - name: Deploy to EC2 Instance 1 (Production)
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_INSTANCE_1 }} # IP o dominio de la instancia EC2 1
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/ec2-user/app
            git pull origin main
            cp -r * /var/www/html # Copiar los archivos estáticos a la carpeta de servidor web

      # Paso 2: Desplegar en la instancia EC2 2 (Producción)
      - name: Deploy to EC2 Instance 2 (Production)
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_INSTANCE_2 }} # IP o dominio de la instancia EC2 2
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/ec2-user/app
            git pull origin main
            cp -r * /var/www/html # Copiar los archivos estáticos a la carpeta de servidor web
