name: CI/CD for Docker Image Deployment DOCKER

on:
  push:
    branches:
      - test  # Desencadenar en la rama de test para construir y subir la imagen

  pull_request:
    branches:
      - master  # Desplegar cuando se haga un PR hac

jobs:
  # Trabajo 1: Construir y subir la imagen Docker (en entorno test)
  update_docker_image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .               # Usa el Dockerfile 
          push: true               # Sube la imagen a Docker Hub
          tags: dayanara1898/html-project:latest

  # Trabajo 2: Crear un pull request autom치ticamente (si es necesario)
  create_pull_request:
    name: Create Pull Request from Test to Master
    runs-on: ubuntu-latest
    needs: update_docker_image  # Depende de que la imagen Docker se haya actualizado
    if: github.ref == 'refs/heads/test'  # Solo se ejecuta si es un push a 'test'

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        uses: github-cli/gh-action@v2
        with:
          gh_token: ${{ secrets.MY_ACCESS_TOKEN }}  # Usando el token secreto para autenticar en la API de GitHub

      - name: Create pull request
        run: |
          gh pr create --base master --head test --title "Auto-PR from test to master" --body "Este es un PR autom치tico creado por GitHub Actions."
      
  # Trabajo 3: Desplegar la imagen en EC2 instancia de test
  deploy_to_test:
    name: Deploy Docker Image to Test EC2 Instance
    runs-on: ubuntu-latest
    needs: update_docker_image
    if: github.ref == 'refs/heads/test' # Solo se ejecuta en un push a 'test'

    steps:
      - name: Set up SSH key for Test Instance
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2 Test Instance
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_INSTANCE }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            docker stop html-container || true
            docker rm html-container || true
            docker pull dayanara1898/html-project:latest
            docker run -d --name html-container -p 80:80 dayanara1898/html-project:latest

  # Trabajo 4: Desplegar la imagen en EC2 instancias de producci칩n
  deploy_to_production:
    name: Deploy Docker Image to EC2 Instances
    runs-on: ubuntu-latest
    needs: create_pull_request  # Depende de que el PR haya sido creado
    if: github.event_name == 'pull_request' && github.event.action == 'opened'  # Se ejecuta solo cuando el PR es abierto

    steps:
      - name: Set up SSH key for Production Instances
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Paso 1: Desplegar en la instancia EC2 1 (Producci칩n)
      - name: Deploy to EC2 Instance 1 (Production)
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_INSTANCE_1 }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            docker stop html-container || true
            docker rm html-container || true
            docker pull dayanara1898/html-project:latest
            docker run -d --name html-container -p 80:80 dayanara1898/html-project:latest

      # Paso 2: Desplegar en la instancia EC2 2 
      - name: Deploy to EC2 Instance 2 (Production)
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_INSTANCE_2 }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            docker stop html-container || true
            docker rm html-container || true
            docker pull dayanara1898/html-project:latest
            docker run -d --name html-container -p 80:80 dayanara1898/html-project:latest
